apiVersion: v1
kind: ConfigMap
metadata:
  name: skillpulse-cm
  namespace: skillpulse
data:
  MYSQL_DATABASE: mysql-service
  MYSQL_USER: skillpulse

--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-cm
  namespace: skillpulse
data:
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_USER: skillpulse
  DB_NAME: skillpulse
      