apiVersion: v1
kind: PersistentVolume
metadata:
  name: skillpulse-pv
 # namespace: skillpulse
  labels:
    app: mysql 
spec:
  storageClassName: manual 
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql

---
