apiVersion: v1
kind: Secret
metadata:
  name: secret-dockercfg
  namespace: skillpulse

type: Opaque  #it is use for general purpose

data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3JkMTIz   #base64 encoded
  MYSQL_PASSWORD: c2tpbGxwdWxzZTEyMw==    #base64 encoded

---

apiVersion: v1
kind: Secret
metadata:
  name: secret-backend
  namespace: skillpulse

type: Opaque  #it is use for general purpose

data:
  DB_PASSWORD: c2tpbGxwdWxzZTEyMw==